### ISSUE TITLE
Più microservizi 

### ISSUE THREAD

**Issue by vladislavbogomolov** [FabrizioCafolla/lumen-docker-infrastructure#8]
Ciao, sinceramente cosi è poco chiaro con un servizio solo. Se ci sono più microservizi? E forse non tutti in lumen?

**Comment by FabrizioCafolla** [comment]
Ciao,

Il progetto ha lo scopo di facilitare lo sviluppo di un microservizio basato su Lumen, questo perché è un framework molto leggero e prestante(rispetto a laravel) e ha molte funzionalità che altri framework non possiedono, di conseguenza si ha la necessità di rendere il codice pronto all'uso per un sistema Docker.

Infatti il progetto in questione facilita ed elimina tutte le procedure che andrebbero eseguite a mano per la creazione di un ambiente di sviluppo e produzione basato sulla tecnologia Docker.

Se nella tua infrastruttura a microservizio necessiti di un servizio backend che espone delle API questo è un progetto che fa per te, ovviamente questo tipo di infrastruttura ti permette di avere più microservizio in esecuzione, e non è detto che siano tutti in PHP però questa è una scelta progettuale.

Grazie
